//{{NO_DEPENDENCIES}}
// Von Microsoft Visual C++ generierte Includedatei.
// Verwendet von SmartLogiLED.rc

#define IDS_APP_TITLE			103

#define IDR_MAINFRAME			128
#define IDD_SMARTLOGILED_DIALOG	102
#define IDD_ABOUTBOX			103
#define IDD_HELPBOX				104
#define IDD_KEYSBOX				105
#define IDD_ADDPROFILEBOX		106
#define IDM_ABOUT				105
#define IDM_HELP				106
#define IDM_EXIT				107
#define IDM_START_MINIMIZED		108
#define IDM_EXPORT_PROFILES		109
#define IDM_IMPORT_PROFILE		110
#define IDM_EXPORT_SELECTED_PROFILE	111
#define IDI_SMARTLOGILED			112
#define IDI_SMALL				113
#define IDC_SMARTLOGILED			114
#define IDC_MYICON				2
#define IDC_STATIC_ICON_ABOUT   122
#define IDC_STATIC_ICON_HELP    123
#ifndef IDC_STATIC
#define IDC_STATIC				-1
#endif

#define IDC_BOX_NUMLOCK 220
#define IDC_BOX_CAPSLOCK 221
#define IDC_BOX_SCROLLLOCK 222
#define IDC_LABEL_NUMLOCK 223
#define IDC_LABEL_CAPSLOCK 224
#define IDC_LABEL_SCROLLLOCK 225
#define IDC_BOX_DEFAULTCOLOR 226
#define IDC_LABEL_DEFAULTCOLOR 227
#define ID_TRAY_OPEN 1001
#define ID_TRAY_CLOSE 1002
#define ID_TRAY_START_MINIMIZED 1003
#define IDC_GROUP_LOCKS 300

// App Profile controls
#define IDC_GROUP_APPPROFILE 301
#define IDC_COMBO_APPPROFILE 302
#define IDC_BUTTON_ADD_PROFILE 303
#define IDC_BUTTON_REMOVE_PROFILE 304
#define IDC_BUTTON_KEYS 305
#define IDC_LABEL_CURRENT_PROFILE 306
#define IDC_BOX_APPCOLOR 307
#define IDC_LABEL_APPCOLOR 308
#define IDC_BOX_APPHIGHLIGHTCOLOR 309
#define IDC_LABEL_APPHIGHLIGHTCOLOR 310
#define IDC_CHECK_LOCK_KEYS_VISUALISATION 311

// Keys Dialog controls
#define IDC_EDIT_KEYS 400
#define IDC_BUTTON_RESET_KEYS 401
#define IDC_BUTTON_DONE_KEYS 402
#define IDC_LABEL_KEYS_INFO 403

// Add Profile Dialog controls
#define IDC_COMBO_APP_SELECTOR 410
#define IDC_BUTTON_DONE_ADD_PROFILE 411
#define IDC_LABEL_ADD_PROFILE_INFO 412

// Nächste Standardwerte für neue Objekte
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NO_MFC					130
#define _APS_NEXT_RESOURCE_VALUE	129
#define _APS_NEXT_COMMAND_VALUE		32771
#define _APS_NEXT_CONTROL_VALUE		1000
#define _APS_NEXT_SYMED_VALUE		110
#endif
#endif
