//{{NO_DEPENDENCIES}}
// Von Microsoft Visual C++ generierte Includedatei.
// Verwendet von SmartLogiLED.rc

#define IDS_APP_TITLE			103

#define IDR_MAINFRAME			128
#define IDD_SMARTLOGILED_DIALOG	102
#define IDD_ABOUTBOX			103
#define IDD_HELPBOX				104
#define IDM_ABOUT				105
#define IDM_HELP				106
#define IDM_EXIT				107
#define IDI_SMARTLOGILED			108
#define IDI_SMALL				109
#define IDC_SMARTLOGILED			110
#define IDC_MYICON				2
#define IDC_STATIC_ICON_ABOUT   122
#define IDC_STATIC_ICON_HELP    123
#ifndef IDC_STATIC
#define IDC_STATIC				-1
#endif

#define IDC_BOX_NUMLOCK 220
#define IDC_BOX_CAPSLOCK 221
#define IDC_BOX_SCROLLLOCK 222
#define IDC_LABEL_NUMLOCK 223
#define IDC_LABEL_CAPSLOCK 224
#define IDC_LABEL_SCROLLLOCK 225
#define IDC_BOX_DEFAULTCOLOR 226
#define IDC_LABEL_DEFAULTCOLOR 227
#define ID_TRAY_OPEN 1001
#define ID_TRAY_CLOSE 1002
#define ID_TRAY_START_MINIMIZED 1003
#define IDC_GROUP_LOCKS 300
#define IDC_BOX_OFFCOLOR 400
#define IDC_LABEL_OFFCOLOR 401


// Nächste Standardwerte für neue Objekte
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NO_MFC					130
#define _APS_NEXT_RESOURCE_VALUE	129
#define _APS_NEXT_COMMAND_VALUE		32771
#define _APS_NEXT_CONTROL_VALUE		1000
#define _APS_NEXT_SYMED_VALUE		110
#endif
#endif
